## Step 1: Import the necessary lib

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Step 2: Import dataset

In [22]:
Dataset=pd.read_csv('KNN Data.csv')

In [23]:
Dataset.head()

Age  Salary  Purchased Plot
0   22   22990               0
1   38   24200               0
2   29   52030               0
3   30   68970               0
4   22   91960               0

In [24]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             400 non-null    int64
 1   Salary          400 non-null    int64
 2   Purchased Plot  400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [25]:
Dataset.isnull().sum()

Age               0
Salary            0
Purchased Plot    0
dtype: int64

In [26]:
d=pd.read_csv('KNN Data (copy).csv')

In [27]:
d.isnull().sum()

Age               1
Salary            1
Purchased Plot    0
dtype: int64

## Step3: Divide Dataset Into Feature Matrix and Output Vector

In [28]:
Dataset.head()

Age  Salary  Purchased Plot
0   22   22990               0
1   38   24200               0
2   29   52030               0
3   30   68970               0
4   22   91960               0

In [29]:
X=Dataset.iloc[:,:-1].values
Y=Dataset.iloc[:,-1].values

In [30]:
X

array([[    22,  22990],
       [    38,  24200],
       [    29,  52030],
       [    30,  68970],
       [    22,  91960],
       [    30,  70180],
       [    30, 101640],
       [    35, 181500],
       [    28,  39930],
       [    38,  78650],
       [    29,  96800],
       [    29,  62920],
       [    23, 104060],
       [    35,  21780],
       [    21,  99220],
       [    32,  96800],
       [    50,  30250],
       [    48,  31460],
       [    49,  33880],
       [    51,  35090],
       [    48,  26620],
       [    50,  59290],
       [    51,  49610],
       [    48,  26620],
       [    49,  27830],
       [    50,  24200],
       [    52,  33880],
       [    50,  36300],
       [    32,  52030],
       [    34,  21780],
       [    34,  89540],
       [    30, 165770],
       [    24,  19360],
       [    31,  53240],
       [    30, 108900],
       [    38,  32670],
       [    36,  33880],
       [    33,  59290],
       [    29,  87120],
       [    30,  37510],


## Step 4: Split the dataset into training set and testing set

In [31]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2)

## Step 5: Building a KNN Classifier

In [32]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier()

In [33]:
KNN.fit(xtrain,ytrain)

KNeighborsClassifier()

## Step 6: Validate the model with text input

In [34]:
ypred=KNN.predict(xtest)

In [35]:
ypred

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [36]:
ytest

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1])

## Step 7: Performance Metric in term of confusion matrix

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
CM=confusion_matrix(ytest,ypred)
CM

array([[49,  6],
       [ 9, 16]])

In [38]:
ytest.shape

(80,)

In [39]:
print(accuracy_score(ytest,ypred))

0.8125


## Precision and Recall Values

In [40]:
print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       0.84      0.89      0.87        55
           1       0.73      0.64      0.68        25

    accuracy                           0.81        80
   macro avg       0.79      0.77      0.77        80
weighted avg       0.81      0.81      0.81        80



## Naive Bias's, Decision Tree and Random Forest as classifier

In [42]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
gnb= GaussianNB()
dtc= DecisionTreeClassifier(criterion='entropy', max_depth=3)
rfc= RandomForestClassifier(n_estimators=700,criterion='entropy')

## Building a Naive Baye's Classifier

In [43]:
gnb.fit(xtrain,ytrain)

GaussianNB()

In [44]:
ypred_gnb = gnb.predict(xtest)

## Testing score and Testing score

In [46]:
print(f"The testing set score of naive bayes Model is {gnb.score(xtest,ytest)}")
print(f"The testing set score of naive bayes Model is {gnb.score(xtrain,ytrain)}")

The testing set score of naive bayes Model is 0.8875
The testing set score of naive bayes Model is 0.896875


In [48]:
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,mean_squared_error, f1_score, recall_score

In [54]:
print(f"The confusion matrix of Naive Bayes Model is")
print(confusion_matrix(ytest,ypred_gnb))
print(f"The  The accuracy score is {accuracy_score(ytest,ypred_gnb)}")
print(f"The precision score is {precision_score(ytest,ypred_gnb,average=None,zero_division=0)}")
print(f"The F1 score is {f1_score(ytest,ypred_gnb)}")
print(f"The MSE score is{mean_squared_error(ytest,ypred_gnb)}")

The confusion matrix of Naive Bayes Model is
[[51  4]
 [ 5 20]]
The  The accuracy score is 0.8875
The precision score is [0.91071429 0.83333333]
The F1 score is 0.816326530612245
The MSE score is0.1125


In [53]:
#### Classification report
from sklearn.metrics import classification_report
print(f"The MSE score is{classification_report(ytest,ypred_gnb)}")

The MSE score is              precision    recall  f1-score   support

           0       0.91      0.93      0.92        55
           1       0.83      0.80      0.82        25

    accuracy                           0.89        80
   macro avg       0.87      0.86      0.87        80
weighted avg       0.89      0.89      0.89        80



## Similarily do it for DT and Random forest. Compare all models and comment on which model need to be used for the given dataset